name: Daily ETF Bot

on:
  schedule:
    - cron: '30 0 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3에서 v4로 업데이트
      - name: Set up Python
        uses: actions/setup-python@v5 # v4에서 v5로 업데이트
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pandas openpyxl requests
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
